name: Publish release image and create release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write
  attestations: write
  id-token: write

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable-publish-release.yml
    with:
      version_prefix: "v"
      image_name: ${{ github.repository }}
    secrets: inherit